name: camo1
channels:
  - pytorch
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
dependencies:
  - cudatoolkit=11.3
  - numpy=1.23.4
  - python=3.9
  - pytorch=1.12.1
  - torchvision=0.11.2
  - tqdm=4.64.1
  - pip
  - pip:
    - opencv-python==4.6.0.66
    - -i https://pypi.tuna.tsinghua.edu.cn/simple

